name: 'Setup Bun Environment'
description: 'Setup Bun and install dependencies'
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.2
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
